// <auto-generated />
namespace EFRelations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Associates_Courses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Associates_Courses));
        
        string IMigrationMetadata.Id
        {
            get { return "202306081238155_Associates_Courses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
